services:
  # osrm-extract:
  #   container_name: osrm-extract
  #   image: osrm/osrm-backend
  #   command: osrm-extract -p /options/bolivia.lua /data/bolivia-latest.osm.pbf
  #   volumes:
  #     - ./data:/data
  #     - ./options:/options
  #   networks:
  #     - compose-net
  
  # osrm-contract:
  #   container_name: osrm-contract
  #   image: osrm/osrm-backend
  #   command: osrm-contract /data/bolivia-latest.osrm
  #   volumes:
  #     - ./data:/data
  #   networks:
  #     - compose-net
  #   depends_on:
  #     - osrm-extract

  osrm-setup:
    # profiles:
    #   - setup
    container_name: osrm-setup
    image: osrm/osrm-backend
    hostname: osrm-setup
    command: sh -c "osrm-extract -p /options/bolivia.lua /data/bolivia-latest.osm.pbf && osrm-contract /data/bolivia-latest.osrm"
    volumes:
      - ./data:/data
      - ./options:/options
    networks:
      - compose-net

  map-osrm-server:
    container_name: map-osrm-server
    image: osrm/osrm-backend
    hostname: map-osrm-server
    command: osrm-routed --algorithm ch /data/bolivia-latest.osrm
    ports:
      - "4300:5000"
    volumes:
      - ./data:/data
    networks:
      - compose-net
    depends_on:
        osrm-setup:
          condition: service_completed_successfully

networks:
  compose-net:
    external: true