services:
  osrm-setup:
    # profiles:
    #   - setup
    container_name: osrm-setup
    image: osrm/osrm-backend:latest
    hostname: osrm-setup
    command: sh -c "osrm-extract -p /options/bolivia.lua /data/geo-data-latest.osm.pbf && osrm-contract /data/geo-data-latest.osrm"
    volumes:
      - ./data:/data
      - ./options:/options
    networks:
      - compose-net

  map-osrm-server:
    container_name: map-osrm-server
    image: osrm/osrm-backend:latest
    hostname: map-osrm-server
    command: osrm-routed --algorithm ch /data/geo-data-latest.osrm
    ports:
      - "4300:5000"
    volumes:
      - ./data:/data
    networks:
      - compose-net
    depends_on:
        osrm-setup:
          condition: service_completed_successfully

networks:
  compose-net:
    external: true